spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3307/myweb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai}
    username: ${MYSQL_USER:myweb}
    password: ${MYSQL_PASSWORD:myweb}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 0
      connection-timeout: 2000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

